# Generated by Django 3.1.4 on 2021-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210206_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
