# Generated by Django 3.1.4 on 2021-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_teacher_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
