# Generated by Django 3.1.4 on 2021-02-07 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210207_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_head', to='management.department'),
        ),
    ]
