# Generated by Django 3.1.4 on 2021-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_teacher_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
