# Generated by Django 3.1.4 on 2021-02-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20210208_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(default=0),
        ),
    ]
